### ISSUE TITLE
Old content shown in search results?

### ISSUE THREAD

**Issue by peteruithoven** [elementary/contributor-docs#19]
### What Happened?

When searching for wingpanel it seems to mention content that is not or no longer on the page:
![Screenshot from 2023-04-15 13 03 50@2x](https://user-images.githubusercontent.com/523210/232210167-1e119c4e-ca73-431a-b997-8623c4a7bed9.png)

### Steps to Reproduce

1. Search for "wingpanel"
2. Click on result

### Expected Behavior

You're brought to the clicked content. 

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment]
We use GitBook for our docs, so I think this would have to be forwarded to them. It looks like they have discussions enabled on GitHub here: https://github.com/orgs/GitbookIO/discussions

Closing as "out of scope" since this repo only contains the content of the documentation itself and we don't have control over the interface or search indexing and things like that
